name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:123456789100:role/my-github-actions-role
          aws-region: us-east-2
          role-session-name: MySessionName

      - name: Manage Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: secretId1, ENV_VAR, secretId2
          parse-json-secrets: (Optional) true|false
      - name: Print secrets
        run: |
          echo "${{ toJSON(steps.<step_name>.outputs.aws-secrets) }}"

