name: Deploy to AWS EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:765681142540:role/my-github-actions-role
          aws-region: us-east-2
      
      - name: Deploy to EC2 instance
        run: |
          # your deployment commands here
