name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:123456789100:role/my-github-actions-role
          aws-region: us-east-2
          role-session-name: MySessionName

      - name: Get Secrets
        id: get-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: ZB_PROMO,TWIN_NEM,PUSH_BULLET
          parse-json-secrets: true

      - name: Print secrets
        run: |
          echo "::set-env name=ZB_PROMO::${{ steps.get-secrets.outputs.ZB_PROMO }}"
          echo "::set-env name=TWIN_NEM::${{ steps.get-secrets.outputs.TWIN_NEM }}"
          echo "::set-env name=PUSH_BULLET::${{ steps.get-secrets.outputs.PUSH_BULLET}}"

